# Generated by Django 3.1.1 on 2020-11-16 16:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='atBus',
            field=models.IntegerField(default=1, max_length=3),
        ),
    ]
