# Generated by Django 3.1.1 on 2020-11-16 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_tbluser_atbus'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='atBus',
            field=models.IntegerField(default=1),
        ),
    ]
