# Generated by Django 3.1.1 on 2020-11-16 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20201116_2149'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluser',
            name='atBus',
            field=models.CharField(default='1', max_length=3),
        ),
    ]
