# Generated by Django 3.1.1 on 2020-11-16 17:15

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('accounts', '0005_auto_20201116_2202'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='user',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='atBus',
            field=models.CharField(default='1', max_length=50),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='userType',
            field=models.CharField(max_length=50),
        ),
    ]
