# Generated by Django 3.1.1 on 2021-01-05 16:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_auto_20201202_1340'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='bill',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='consumedUnits',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='currActiveLoad',
            field=models.FloatField(default=0),
        ),
        migrations.AddField(
            model_name='tbluser',
            name='currReactiveLoad',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='tbluser',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
