# Generated by Django 3.1.1 on 2021-01-13 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_auto_20210105_2128'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluser',
            name='lastTime',
            field=models.CharField(default='00:00:00', max_length=20),
        ),
    ]
