# Generated by Django 3.1.5 on 2021-05-30 07:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0010_auto_20210114_0022'),
    ]

    operations = [
        migrations.DeleteModel(
            name='tblUser',
        ),
    ]
